-- 1:1 matching Plus: 30-day entitlement and rolling recommendation refresh limits.

begin;

create table if not exists public.dating_1on1_plus_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null,
  updated_at timestamptz not null default now(),
  constraint dating_1on1_plus_subscription_dates_check check (expires_at > starts_at)
);

create index if not exists idx_dating_1on1_plus_active
  on public.dating_1on1_plus_subscriptions (expires_at desc);

alter table public.dating_1on1_plus_subscriptions enable row level security;
drop policy if exists "dating_1on1_plus_select_own" on public.dating_1on1_plus_subscriptions;
create policy "dating_1on1_plus_select_own"
  on public.dating_1on1_plus_subscriptions for select
  using (auth.uid() = user_id);

create table if not exists public.dating_1on1_plus_grants (
  grant_key text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  duration_days integer not null,
  created_at timestamptz not null default now(),
  constraint dating_1on1_plus_grant_days_check check (duration_days between 1 and 365)
);

alter table public.dating_1on1_plus_grants enable row level security;

create or replace function public.grant_dating_1on1_plus(
  p_user_id uuid,
  p_grant_key text,
  p_duration_days integer default 30
)
returns table (starts_at timestamptz, expires_at timestamptz, already_granted boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_existing public.dating_1on1_plus_subscriptions%rowtype;
  v_starts_at timestamptz;
  v_expires_at timestamptz;
begin
  if p_user_id is null or coalesce(trim(p_grant_key), '') = '' then
    raise exception 'user_id and grant_key are required';
  end if;
  if p_duration_days < 1 or p_duration_days > 365 then
    raise exception 'duration_days must be between 1 and 365';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));
  select * into v_existing
  from public.dating_1on1_plus_subscriptions
  where user_id = p_user_id;

  if exists (select 1 from public.dating_1on1_plus_grants where grant_key = p_grant_key) then
    return query select v_existing.starts_at, v_existing.expires_at, true;
    return;
  end if;

  v_starts_at := case
    when v_existing.user_id is not null and v_existing.expires_at > v_now then v_existing.starts_at
    else v_now
  end;
  v_expires_at := greatest(coalesce(v_existing.expires_at, v_now), v_now)
    + make_interval(days => p_duration_days);

  insert into public.dating_1on1_plus_grants (grant_key, user_id, duration_days)
  values (p_grant_key, p_user_id, p_duration_days);

  insert into public.dating_1on1_plus_subscriptions (user_id, starts_at, expires_at, updated_at)
  values (p_user_id, v_starts_at, v_expires_at, v_now)
  on conflict (user_id) do update set
    starts_at = excluded.starts_at,
    expires_at = excluded.expires_at,
    updated_at = excluded.updated_at;

  return query select v_starts_at, v_expires_at, false;
end;
$$;

revoke all on function public.grant_dating_1on1_plus(uuid, text, integer) from public;
revoke all on function public.grant_dating_1on1_plus(uuid, text, integer) from anon;
revoke all on function public.grant_dating_1on1_plus(uuid, text, integer) from authenticated;
grant execute on function public.grant_dating_1on1_plus(uuid, text, integer) to service_role;

create table if not exists public.dating_1on1_recommendation_refresh_events (
  id bigint generated by default as identity primary key,
  card_id uuid not null references public.dating_1on1_cards(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  refreshed_at timestamptz not null default now()
);

create index if not exists idx_dating_1on1_refresh_events_card_time
  on public.dating_1on1_recommendation_refresh_events (card_id, refreshed_at desc);

alter table public.dating_1on1_recommendation_refresh_events enable row level security;

create or replace function public.consume_dating_1on1_recommendation_refresh(
  p_card_id uuid,
  p_user_id uuid,
  p_limit integer
)
returns table (
  allowed boolean,
  used_count integer,
  remaining_count integer,
  refreshed_at timestamptz,
  next_refresh_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_window_start timestamptz := v_now - interval '24 hours';
  v_card public.dating_1on1_cards%rowtype;
  v_used_count integer := 0;
  v_oldest_refresh timestamptz;
begin
  if p_card_id is null or p_user_id is null then
    raise exception 'card_id and user_id are required';
  end if;
  if p_limit < 1 or p_limit > 10 then
    raise exception 'refresh limit must be between 1 and 10';
  end if;

  select * into v_card
  from public.dating_1on1_cards
  where id = p_card_id
  for update;

  if v_card.id is null then
    raise exception '1:1 card not found';
  end if;
  if v_card.user_id <> p_user_id then
    raise exception 'only the card owner can refresh recommendations';
  end if;
  if v_card.status not in ('submitted', 'reviewing', 'approved') then
    raise exception '1:1 card is not active';
  end if;

  delete from public.dating_1on1_recommendation_refresh_events as refresh_event
  where refresh_event.card_id = p_card_id
    and refresh_event.refreshed_at < v_now - interval '7 days';

  select count(*)::integer, min(event.refreshed_at)
  into v_used_count, v_oldest_refresh
  from public.dating_1on1_recommendation_refresh_events event
  where event.card_id = p_card_id
    and event.refreshed_at > v_window_start;

  if v_used_count = 0
    and v_card.recommendation_refresh_used_at is not null
    and v_card.recommendation_refresh_used_at > v_window_start then
    insert into public.dating_1on1_recommendation_refresh_events (card_id, user_id, refreshed_at)
    values (p_card_id, p_user_id, v_card.recommendation_refresh_used_at);
    v_used_count := 1;
    v_oldest_refresh := v_card.recommendation_refresh_used_at;
  end if;

  if v_used_count >= p_limit then
    return query select false, v_used_count, 0, null::timestamptz, v_oldest_refresh + interval '24 hours';
    return;
  end if;

  insert into public.dating_1on1_recommendation_refresh_events (card_id, user_id, refreshed_at)
  values (p_card_id, p_user_id, v_now);

  update public.dating_1on1_cards
  set recommendation_refresh_used_at = v_now,
      updated_at = v_now
  where id = p_card_id;

  v_used_count := v_used_count + 1;
  if v_oldest_refresh is null then
    v_oldest_refresh := v_now;
  end if;

  return query select
    true,
    v_used_count,
    greatest(p_limit - v_used_count, 0),
    v_now,
    case when v_used_count >= p_limit then v_oldest_refresh + interval '24 hours' else null end;
end;
$$;

revoke all on function public.consume_dating_1on1_recommendation_refresh(uuid, uuid, integer) from public;
revoke all on function public.consume_dating_1on1_recommendation_refresh(uuid, uuid, integer) from anon;
revoke all on function public.consume_dating_1on1_recommendation_refresh(uuid, uuid, integer) from authenticated;
grant execute on function public.consume_dating_1on1_recommendation_refresh(uuid, uuid, integer) to service_role;

alter table public.toss_test_payment_orders
  drop constraint if exists toss_test_payment_orders_product_type_check;

alter table public.toss_test_payment_orders
  add constraint toss_test_payment_orders_product_type_check
  check (product_type in (
    'apply_credits',
    'paid_card',
    'more_view',
    'city_view',
    'one_on_one_contact_exchange',
    'one_on_one_priority_24h',
    'one_on_one_plus_30d',
    'swipe_premium_30d',
    'love_fortune_detail'
  ));

commit;

notify pgrst, 'reload schema';
