begin;

create index if not exists idx_toss_test_payment_orders_approved_at
  on public.toss_test_payment_orders (approved_at desc)
  where approved_at is not null;

create table if not exists public.payment_funnel_events (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  session_id text null,
  event_name text not null check (event_name in ('view_item', 'select_item')),
  product_type text not null,
  item_name text null,
  amount int not null default 0 check (amount >= 0),
  placement text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_payment_funnel_events_created
  on public.payment_funnel_events (created_at desc);

create index if not exists idx_payment_funnel_events_product_created
  on public.payment_funnel_events (product_type, created_at desc);

create index if not exists idx_payment_funnel_events_user_created
  on public.payment_funnel_events (user_id, created_at desc)
  where user_id is not null;

alter table public.payment_funnel_events enable row level security;

drop policy if exists "payment_funnel_events_admin_select" on public.payment_funnel_events;
create policy "payment_funnel_events_admin_select"
  on public.payment_funnel_events for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.user_id = auth.uid()
        and p.role = 'admin'
    )
  );

commit;

notify pgrst, 'reload schema';
