export const DATING_PAID_FIXED_HOURS = 36;
export const DATING_PAID_FIXED_MS = DATING_PAID_FIXED_HOURS * 60 * 60 * 1000;
export const DATING_PAID_FIXED_LABEL = `${DATING_PAID_FIXED_HOURS}시간 상단고정`;
export const DATING_PAID_FIXED_SHORT_LABEL = `${DATING_PAID_FIXED_HOURS}h 상단고정`;
export const DATING_PAID_FIXED_BADGE_LABEL = `🔥${DATING_PAID_FIXED_HOURS}시간 고정`;
